### ISSUE TITLE
[Feature Request] PIN shouldn't be visible

### ISSUE THREAD

**Issue by coolacid** [FutureTense/lock-manager#74]
**Is your feature request related to a problem? Please describe.**
People tend to use the same pin number for multiple things, as such, it would be very nice to either have a version, or config generated where the pin number isn't visible anywhere directly. 

**Describe the solution you'd like**
The PIN number is hidden, and never actually visible in any panel. 

**Describe alternatives you've considered**
None at this point, however, I did try adding the `password` mode to the PIN `input_text` which hid the value in the input, however, still shows in the debug (which I will remove manually as well) but still shows up in the history and timeline. It would be better to just list "Changed by [user]" without what it was changed to. 

**Additional context**

**Comment by firstof9** [comment]
The sensor is used to confirm the PINs have been set, if you'd like the PIN not to show in your history you can exclude the sensors via your `configuration.yaml`.

If you are worried about other users accessing this information, lock them out of the view.

**Comment by coolacid** [comment]
I already lock people out of the view. However, I also don't want to see people's pin numbers since I have no reason to know it.

**Comment by raman325** [comment]
In order to get a nice view of the PINs that the integration provides, the PIN state needs to be stored. There is currently no way to "hide" or obfuscate data in HomeAssistant, so we can't really do anything to address the visibility in Developer Tools or History, we can just set the mode of the input_text to password to hide it in Lovelace. Your alternative is to set and clear usercodes using the `ozw`/`zwave` services, but then you don't get the nice view nor does this integration provide you any value.

**Comment by firstof9** [comment]
Technically the history can be omitted via excludes to recorder, history and logbook configuration entries.
